title: "Mundana"
description: "Mundana is a free Jekyll theme for awesome people like you, Medium like."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: "/mundana-theme-jekyll"
disqus: "demowebsite"
email: "wowthemesnet@gmail.com"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

# Use the theme
theme: mundana-jekyll

include:
  - "_pages"

permalink: "/:title/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  sal:
    name: Sal
    site: https://www.wowthemes.net
    avatar: /assets/images/avatar1.jpg
    bio: "Hi, I am Sal, the author of Mundana."
    email: wowthemesnet@gmail.com
    twitter: https://twitter.com/wowthemesnet

  jane:
    name: Jane
    site: https://www.wowthemes.net
    avatar: /assets/images/avatar2.jpg
    bio: "Blogger & fashionista!"
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  - scope:
      path: "_pages"
    values:
      layout: page

markdown: kramdown
highlighter: rouge

paginate: 10

exclude:
  - README.markdown
  - package.json
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - node_modules
  - Gemfile
  - Gemfile.lock
